oneself:
  swagger: # swagger 主页配置
    enable: true # 开启 Swagger 主页配置，默认 false
    base-package: com.oneself # 扫描的包名，默认扫描 com.oneself 包下的所有接口
    title: oneself-stream-compute # 接口文档标题，默认 oneself
    description: oneself-stream-compute description # 接口文档描述，默认 oneself description
    group-name: oneself-stream-compute # 接口文档分组名称，默认 oneself


feign:
  sentinel:
    enabled: true

spring:
  config:
    import:
      - nacos:${spring.application.name}-${spring.profiles.active}.yaml?refreshEnabled=true
  cloud:
    sentinel:
      transport:
        dashboard: 127.0.0.1:8090 # Sentinel 地址
    nacos:
      server-addr: 127.0.0.1:8848 # Nacos 地址
      config:
        import-check:
          enabled: false # 校验 Nacos 配置中心的配置文件是否存在
        file-extension: yaml # 在 Nacos 的文件后缀名
        group: DEFAULT_GROUP # 配置组名，可以自定义
        refresh-enabled: true # 启用自动刷新配置
        namespace: dev # 配置命名空间，使用命名空间唯一 ID
      discovery:
        cluster-name: dev # 设置 Nacos 的集群属性
        namespace: dev # 配置命名空间，使用命名空间唯一 ID
  datasource:
    dynamic:
      primary: postgres
      strict: false
      datasource:
        mysql:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/oneself_stream_compute?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai&useSSL=false
          username: liuhuan
          password: Z6eQaNaitK5vSX
        postgres:
          driver-class-name: org.postgresql.Driver
          url: jdbc:postgresql://127.0.0.1:5432/oneself?currentSchema=oneself_stream_compute&useUnicode=true&characterEncoding=utf-8
          username: admin
          password: PK3uK7pUIwUTi1
