spring:
  application:
    name: oneself-common

oneself:
  swagger:
    enable: false
    title: oneself-common
    description: oneself-common
    version: 1.0.0
    base-package: com.oneself.common
  file:
    ftp:
      host: "ftp.example.com"
      port: 21
      user: "ftpUser"
      password: "ftpPassword"
    sftp:
      host: "sftp.example.com"
      port: 22
      user: "ftpUser"
      password: "ftpPassword"
