server:
  port: 9100
  servlet:
    session:
      timeout: 600

spring:
  application:
    name: oneself-gateway
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848 # Nacos 地址
      config:
        import-check:
          enabled: false # 校验 Nacos 配置中心的配置文件是否存在
        file-extension: yaml # 在 Nacos 的文件后缀名
        group: DEFAULT_GROUP # 配置组名，可以自定义
        refresh-enabled: true # 启用自动刷新配置
        namespace: dev # 配置命名空间，使用命名空间唯一 ID
      discovery:
        cluster-name: dev # 设置 Nacos 的集群属性
        namespace: dev # 配置命名空间，使用命名空间唯一 ID
#    gateway:
#      routes: # 路由配置
#        - id: oneself-demo # 路由 id 自定义 只要唯一即可
#          uri: lb://oneself-demo # 路由的目标地址 lb 就是负载均衡，后面跟服务名称
#          predicates: # 路由断言，也就是判断请是否符合路由规则的条件
#            - Path=/oneself-demo/** # /order 开头的请求访问 service-order
