oneself:
  swagger:
    enable: true
#    title: oneself-demo
#    description: oneself-demo API 文档
#    version: 1.0.0
#    base-package: com.oneself
#    service-url: http://127.0.0.1:9011/oneself-demo
  elasticsearch:
    enabled: true
    nodes:
      - "127.0.0.1:9200"
    connect-timeout: 5000
    socket-timeout: 60000
    max-connections: 100
    max-connections-per-route: 10

spring:
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848 # Nacos 地址
      config:
        import-check:
          enabled: false # 校验 Nacos 配置中心的配置文件是否存在
        file-extension: yaml # 在 Nacos 的文件后缀名
        group: DEFAULT_GROUP # 配置组名，可以自定义
        refresh-enabled: true # 启用自动刷新配置
        namespace: dev # 配置命名空间，使用命名空间唯一 ID
      discovery:
        cluster-name: dev # 设置 Nacos 的集群属性
        namespace: dev # 配置命名空间，使用命名空间唯一 ID
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/oneself-demo?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: liuhuan
    password: Z6eQaNaitK5vSX
