spring:
  application:
    name: oneself-demo
  profiles:
    active: dev # 设置为开发环境
#  config:
#    use-legacy-processing: true # Spring Boot 2.4.0 开始，bootstrap.yml 被废弃，显式启用 bootstrap.yml

server:
  port: 8081 # 8080 端口被 Jenkins 占用，改为 8081
  servlet:
    context-path: /oneself-demo
    session:
      timeout: 600