oneself:
  elasticsearch:
    enabled: true
    nodes:
      - "127.0.0.1:9200"
    connect-timeout: 5000
    socket-timeout: 60000
    max-connections: 100
    max-connections-per-route: 10

spring:
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848 # Nacos 地址
      config:
        import-check:
          enabled: false # 校验 Nacos 配置中心的配置文件是否存在
        file-extension: yaml # 在 Nacos 的文件后缀名
        group: DEFAULT_GROUP # 配置组名，可以自定义
        refresh-enabled: true # 启用自动刷新配置
        namespace: dev # 配置命名空间，使用命名空间唯一 ID
      discovery:
        cluster-name: dev # 设置 Nacos 的集群属性
        namespace: dev # 配置命名空间，使用命名空间唯一 ID
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/oneself-demo?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: liuhuan
    password: Z6eQaNaitK5vSX

knife4j:
  enable: true # 开启增强配置，启用 Knife4j 功能
  documents: # 自定义文档集合，该属性是数组
    - group: 2.X版本 # 所属分组
      name: 接口签名 # 类似于接口中的 tag，对于自定义文档的分组
      locations: classpath:sign/* # markdown 文件路径,可以是一个文件夹
  setting: # 前端 Ui 的个性化配置属性
    language: zh-CN # 文档界面语言，默认中文 (zh-CN)，也可设置为英文 (en-US)
    enable-swagger-models: true # 是否显示界面中 Swagger Model 功能，默认开启
    enable-document-manage: true # 是否显示文档管理功能，默认开启
    swagger-model-name: Swagger Models # 重命名 Swagger Model 名称，默认 Swagger Models
    enable-version: false # 是否开启界面中对某接口的版本控制，如果开启，后端变化后 Ui 界面会存在小蓝点，默认关闭
    enable-reload-cache-parameter: false # 是否在每个 Debug 调试栏后显示刷新变量按钮，默认不显示
    enable-after-script: true # 调试 Tab 是否显示 AfterScript 功能，默认开启
    enable-filter-multipart-api-method-type: POST # 具体接口的过滤类型
    enable-filter-multipart-apis: false # 针对 RequestMapping 的接口请求类型，在不指定参数类型的情况下，如果不过滤，默认会显示 7 个类型的接口地址参数,如果开启此配置,默认展示一个 Post 类型的接口地址
    enable-request-cache: true # 是否开启请求参数缓存，默认开启
    enable-host: false # 是否启用 Host，默认关闭
    enable-host-text: false # HOST 地址，默认当前服务地址
    enable-home-custom: false # 是否使用自定义主页内容，默认关闭
    home-custom-path: classpath:markdown/home.md # 自定义主页内容的 Markdown 文件路径
    enable-search: false # 是否禁用 Ui 界面中的搜索框，默认不禁止
    enable-footer: true # 是否显示 Footer，默认显示
    enable-footer-custom: false # 是否开启自定义 Footer，默认关闭
    footer-custom-content: GitHub-[oneself](https://github.com/crane0927) # 自定义 Footer 内容
    enable-dynamic-parameter: false # 是否开启动态参数调试功能，默认关闭
    enable-debug: true # 启用调试，默认开启
    enable-open-api: true # 显示 OpenAPI 规范，默认开启
    enable-group: true # 显示服务分组，默认开启
  cors: false # 是否开启一个默认的跨域配置，该功能配合自定义 Host 使用
  production: false # 是否开启生产环境保护策略，生产环境中会隐藏 Swagger 界面
  basic: # 用户认证配置
    enable: true # 是否启用用户认证功能
    username: dev # 用户名，用于登录 Swagger 界面
    password: dev123 # 密码，用于登录 Swagger 界面