spring:
  application:
    name: oneself-ai
  profiles:
    active: dev # 设置为开发环境
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: deepseek-r1:8b


server:
  port: 9103
  servlet:
    context-path: /oneself-ai
    session:
      timeout: 600