oneself:
  swagger: # swagger 主页配置
    enable: true # 开启 Swagger 主页配置，默认 false
    base-package: com.oneself # 扫描的包名，默认扫描 com.oneself 包下的所有接口
    title: oneself-ai # 接口文档标题，默认 oneself
    description: oneself-ai description # 接口文档描述，默认 oneself description
    group-name: oneself-ai # 接口文档分组名称，默认 oneself

spring:
  config:
    import:
      - nacos:${spring.application.name}-${spring.profiles.active}.yaml?refreshEnabled=true
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848 # Nacos 地址
      config:
        import-check:
          enabled: false # 校验 Nacos 配置中心的配置文件是否存在
        file-extension: yaml # 在 Nacos 的文件后缀名
        group: DEFAULT_GROUP # 配置组名，可以自定义
        refresh-enabled: true # 启用自动刷新配置
        namespace: dev # 配置命名空间，使用命名空间唯一 ID
      discovery:
        cluster-name: dev # 设置 Nacos 的集群属性
        namespace: dev # 配置命名空间，使用命名空间唯一 ID
