oneself:
  swagger:
    enable: true
    base-package: com.oneself
    title: oneself-auth
    description: oneself-auth description
    group-name: oneself-auth

spring:
  config:
    import:
      - nacos:${spring.application.name}-${spring.profiles.active}.yaml?refreshEnabled=true
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        import-check:
          enabled: false
        file-extension: yaml
        group: DEFAULT_GROUP
        refresh-enabled: true
        namespace: dev
      discovery:
        cluster-name: dev
        namespace:
  datasource:
    dynamic:
      primary: postgres
      strict: false
      datasource:
        mysql:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/oneself_auth?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai&useSSL=false
          username: liuhuan
          password: Z6eQaNaitK5vSX
        postgres:
          driver-class-name: org.postgresql.Driver
          url: jdbc:postgresql://127.0.0.1:5432/oneself?currentSchema=oneself_auth&useUnicode=true&characterEncoding=utf-8
          username: admin
          password: PK3uK7pUIwUTi1
  data:
    redis:
      host: localhost
      port: 6379
      password: mBYFyN4wXi6WsA
      database: 0
      timeout: 10s
      client-type: lettuce
      lettuce:
        pool:
          enabled: true
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
