spring:
  application:
    name: oneself-system
  profiles:
    active: dev # 设置为开发环境
#  config:
#    use-legacy-processing: true # Spring Boot 2.4.0 开始，bootstrap.yml 被废弃，显式启用 bootstrap.yml

server:
  port: 9010
  servlet:
    context-path: /oneself-system
    session:
      timeout: 600